/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaptainRouteImport } from './routes/captain'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurseRouteImport } from './routes/purse'
import { Route as RostersRouteImport } from './routes/rosters'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainRoute = CaptainRouteImport.update({
  id: '/captain',
  path: '/captain',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurseRoute = PurseRouteImport.update({
  id: '/purse',
  path: '/purse',
  getParentRoute: () => rootRouteImport,
} as any)
const RostersRoute = RostersRouteImport.update({
  id: '/rosters',
  path: '/rosters',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/captain': typeof CaptainRoute
  '/ops': typeof OpsRoute
  '/photos': typeof PhotosRoute
  '/profile': typeof ProfileRoute
  '/purse': typeof PurseRoute
  '/rosters': typeof RostersRoute
  '/schedule': typeof ScheduleRoute
  '/scout': typeof ScoutRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/captain': typeof CaptainRoute
  '/ops': typeof OpsRoute
  '/photos': typeof PhotosRoute
  '/profile': typeof ProfileRoute
  '/purse': typeof PurseRoute
  '/rosters': typeof RostersRoute
  '/schedule': typeof ScheduleRoute
  '/scout': typeof ScoutRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/captain': typeof CaptainRoute
  '/ops': typeof OpsRoute
  '/photos': typeof PhotosRoute
  '/profile': typeof ProfileRoute
  '/purse': typeof PurseRoute
  '/rosters': typeof RostersRoute
  '/schedule': typeof ScheduleRoute
  '/scout': typeof ScoutRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/captain'
    | '/ops'
    | '/photos'
    | '/profile'
    | '/purse'
    | '/rosters'
    | '/schedule'
    | '/scout'
    | '/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/captain'
    | '/ops'
    | '/photos'
    | '/profile'
    | '/purse'
    | '/rosters'
    | '/schedule'
    | '/scout'
    | '/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/captain'
    | '/ops'
    | '/photos'
    | '/profile'
    | '/purse'
    | '/rosters'
    | '/schedule'
    | '/scout'
    | '/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CaptainRoute: typeof CaptainRoute
  OpsRoute: typeof OpsRoute
  PhotosRoute: typeof PhotosRoute
  ProfileRoute: typeof ProfileRoute
  PurseRoute: typeof PurseRoute
  RostersRoute: typeof RostersRoute
  ScheduleRoute: typeof ScheduleRoute
  ScoutRoute: typeof ScoutRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain': {
      id: '/captain'
      path: '/captain'
      fullPath: '/captain'
      preLoaderRoute: typeof CaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purse': {
      id: '/purse'
      path: '/purse'
      fullPath: '/purse'
      preLoaderRoute: typeof PurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosters': {
      id: '/rosters'
      path: '/rosters'
      fullPath: '/rosters'
      preLoaderRoute: typeof RostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CaptainRoute: CaptainRoute,
  OpsRoute: OpsRoute,
  PhotosRoute: PhotosRoute,
  ProfileRoute: ProfileRoute,
  PurseRoute: PurseRoute,
  RostersRoute: RostersRoute,
  ScheduleRoute: ScheduleRoute,
  ScoutRoute: ScoutRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
